### ISSUE TITLE
tape as a dev dependency 

### ISSUE THREAD

**Issue by abdhalees** [FACG4/countires#13]
https://github.com/FACG4/countires/blob/6950b6227c5fcd70e9de46218205b6bcf7f5c658/package.json#L25

The dependency object in `package.json` is for the modules that the server needs to install in order to work. some dependencies are only used in the development phase and they are not essential for the server so they would be installed as a dev dependency.
since `tape` is used only for testing it's better to be a dev dependency.

**Comment by haneenshahwan4** [comment]
done
